// CNode/vue-ssr( nuxt.js )/components/Navigation.vue
<template>
  <div class="navigation">
    <nuxt-link to="/all" active-class='active'>全部</nuxt-link>
    <nuxt-link to="/good" active-class='active'>精华</nuxt-link>
    <nuxt-link to="/share" active-class='active'>分享</nuxt-link>
    <nuxt-link to="/ask" active-class='active'>问答</nuxt-link>
    <nuxt-link to="/job" active-class='active'>招聘</nuxt-link>
    <nuxt-link to="/dev" active-class='active'>客户端测试</nuxt-link>
  </div>
</template>

<style scoped>
.navigation{
  display: flex; 
  justify-content: center;
}
.navigation a{
  padding: 5px 10px;
  background-color: #fff;
  border-radius: 4px;
  text-decoration: none;
}
a.active {
  color: #fff;
  background: blue;
}
</style>

// CNode/cNode(react & ts)/src/pages/home/MainContentList/Navigation/Navigation.tsx
import * as React from 'react';
import './Navigation.css';
import { NavLink } from 'react-router-dom'; 

class Navigation extends React.Component<any, any> {
  constructor(props: any) {
    super(props);
  }
  render() {
    return (
      <div className="navigation">
        <NavLink 
          className={!this.props.tab ? 'selected' : ''}
          to="/list/all"
          activeClassName="selected"
        >全部
        </NavLink>

        <NavLink 
          to="/list/good"
          activeClassName="selected"
        >精华
        </NavLink>

        <NavLink 
          to="/list/share"
          activeClassName="selected"
        >分享
        </NavLink>

        <NavLink 
          to="/list/ask"
          activeClassName="selected"
        >问答
        </NavLink>
        
        <NavLink 
          to="/list/job"
          activeClassName="selected"
        >招聘
        </NavLink>

        <NavLink 
          to="/list/dev"
          activeClassName="selected"
        >客户端测试
        </NavLink>
      </div>
    );
  }
}

export default Navigation;
